version: 0.0
os: linux
files:
  - source: ./dist/my-angular-project/
    destination: /var/www/html/

permissions:
  - object: /var/www/html
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory

hooks:
  BeforeInstall:
     - location: hooks/afterinstall.sh
       timeout: 180
  AfterInstall:
     - location: hooks/before_install.sh
       timeout: 180      